# Generated by Django 3.0.2 on 2020-01-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='eventid',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
